/* Bahasa sumber yang dikenali Whisper untuk fitur Auto Lirik Spectrum. */
export const WHISPER_LANGUAGES: { code: string; label: string }[] = [
  { code: "auto", label: "🌐 Deteksi otomatis" },
  { code: "af", label: "Afrikaans" },
  { code: "am", label: "Amharic" },
  { code: "ar", label: "العربية / Arab" },
  { code: "as", label: "অসমীয়া / Assamese (India)" },
  { code: "az", label: "Azərbaycan / Azerbaijani" },
  { code: "ba", label: "Bashkir" },
  { code: "be", label: "Belarusian" },
  { code: "bg", label: "Български / Bulgarian" },
  { code: "bn", label: "বাংলা / Bengali (India/Bangladesh)" },
  { code: "bo", label: "Tibetan" },
  { code: "br", label: "Breton" },
  { code: "bs", label: "Bosnian" },
  { code: "ca", label: "Català / Catalan" },
  { code: "cs", label: "Čeština / Czech" },
  { code: "cy", label: "Cymraeg / Welsh" },
  { code: "da", label: "Dansk / Danish" },
  { code: "de", label: "Deutsch / German" },
  { code: "el", label: "Ελληνικά / Greek" },
  { code: "en", label: "English" },
  { code: "es", label: "Español / Spanish" },
  { code: "et", label: "Eesti / Estonian" },
  { code: "eu", label: "Euskara / Basque" },
  { code: "fa", label: "فارسی / Persia" },
  { code: "fi", label: "Suomi / Finnish" },
  { code: "fo", label: "Faroese" },
  { code: "fr", label: "Français / French" },
  { code: "gl", label: "Galego / Galician" },
  { code: "gu", label: "ગુજરાતી / Gujarati (India)" },
  { code: "ha", label: "Hausa" },
  { code: "haw", label: "Hawaiian" },
  { code: "he", label: "עברית / Hebrew" },
  { code: "hi", label: "हिन्दी / Hindi (India)" },
  { code: "hr", label: "Hrvatski / Croatian" },
  { code: "ht", label: "Haitian Creole" },
  { code: "hu", label: "Magyar / Hungarian" },
  { code: "hy", label: "Հայերեն / Armenian" },
  { code: "id", label: "🇮🇩 Bahasa Indonesia" },
  { code: "is", label: "Íslenska / Icelandic" },
  { code: "it", label: "Italiano / Italian" },
  { code: "ja", label: "🇯🇵 日本語 / Japanese" },
  { code: "jw", label: "🇮🇩 Basa Jawa / Javanese" },
  { code: "ka", label: "ქართული / Georgian" },
  { code: "kk", label: "Қазақша / Kazakh" },
  { code: "km", label: "Khmer" },
  { code: "kn", label: "ಕನ್ನಡ / Kannada (India)" },
  { code: "ko", label: "🇰🇷 한국어 / Korean" },
  { code: "la", label: "Latin" },
  { code: "lb", label: "Luxembourgish" },
  { code: "ln", label: "Lingala" },
  { code: "lo", label: "Lao" },
  { code: "lt", label: "Lietuvių / Lithuanian" },
  { code: "lv", label: "Latviešu / Latvian" },
  { code: "mg", label: "Malagasy" },
  { code: "mi", label: "Māori" },
  { code: "mk", label: "Македонски / Macedonian" },
  { code: "ml", label: "മലയാളം / Malayalam (India)" },
  { code: "mn", label: "Mongolian" },
  { code: "mr", label: "मराठी / Marathi (India)" },
  { code: "ms", label: "🇲🇾 Bahasa Melayu" },
  { code: "mt", label: "Malti / Maltese" },
  { code: "my", label: "Myanmar / Burmese" },
  { code: "ne", label: "नेपाली / Nepali (India/Nepal)" },
  { code: "nl", label: "Nederlands / Dutch" },
  { code: "nn", label: "Nynorsk" },
  { code: "no", label: "Norsk / Norwegian" },
  { code: "oc", label: "Occitan" },
  { code: "pa", label: "ਪੰਜਾਬੀ / Punjabi (India)" },
  { code: "pl", label: "Polski / Polish" },
  { code: "ps", label: "پښتو / Pashto" },
  { code: "pt", label: "Português / Portuguese" },
  { code: "ro", label: "Română / Romanian" },
  { code: "ru", label: "Русский / Russian" },
  { code: "sa", label: "संस्कृत / Sanskrit (India)" },
  { code: "sd", label: "سنڌي / Sindhi" },
  { code: "si", label: "සිංහල / Sinhala" },
  { code: "sk", label: "Slovenčina / Slovak" },
  { code: "sl", label: "Slovenščina / Slovenian" },
  { code: "sn", label: "Shona" },
  { code: "so", label: "Somali" },
  { code: "sq", label: "Shqip / Albanian" },
  { code: "sr", label: "Српски / Serbian" },
  { code: "su", label: "🇮🇩 Basa Sunda / Sundanese" },
  { code: "sv", label: "Svenska / Swedish" },
  { code: "sw", label: "Kiswahili / Swahili" },
  { code: "ta", label: "தமிழ் / Tamil (India)" },
  { code: "te", label: "తెలుగు / Telugu (India)" },
  { code: "tg", label: "Тоҷикӣ / Tajik" },
  { code: "th", label: "ไทย / Thai" },
  { code: "tk", label: "Turkmen" },
  { code: "tl", label: "Tagalog / Filipino" },
  { code: "tr", label: "🇹🇷 Türkçe / Turkish" },
  { code: "tt", label: "Tatar" },
  { code: "uk", label: "Українська / Ukrainian" },
  { code: "ur", label: "اردو / Urdu (India/Pakistan)" },
  { code: "uz", label: "Oʻzbek / Uzbek" },
  { code: "vi", label: "Tiếng Việt / Vietnamese" },
  { code: "yi", label: "Yiddish" },
  { code: "yo", label: "Yorùbá / Yoruba" },
  { code: "zh", label: "中文 / Chinese" },
  { code: "zu", label: "Zulu" },
];
